- name: Copy for linux
  hosts: webservers
  tasks:
   - name: Copy your file to the webservers
     copy:
       src: /home/ec2-user/Ders2/testfile1
       dest: /home/ec2-user/testfile1

- name: Copy for ubuntu
  hosts: ubuntuservers
  tasks:
   - name: Copy your file to the ubuntuservers
     copy:
       src: /home/ec2-user/Ders2/testfile1
       dest: /home/ubuntu/testfile1

- name: Copy to all servers
  hosts: "*"
  tasks:
   - copy:
       src: home/ec2-user/Ders2/testfile2
       dest: /~/testfile2
